In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.5'

In [3]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [4]:
origin_list = [2, 3, 4]
a = np.array(origin_list)
a

array([2, 3, 4])

In [5]:
print(a.dtype)
print(a.shape)
print(a.ndim)

int64
(3,)
1


In [6]:
c = np.array(origin_list * 5)
c

array([2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4])

In [7]:
c = np.array([1.2, 3.5, 5.1])
print(c)
print(c.dtype)

[1.2 3.5 5.1]
float64


In [8]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
print(b.dtype, b.shape, b.ndim)

float64 (2, 3) 2


In [10]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
print(c.dtype, c.shape, c.ndim)

complex128 (2, 2) 2


In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2, 3, 4), dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
temp = np.empty((2, 3))                     #未初始化，输出可能不同
print(temp)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [17]:
np.full((2, 3), 5.2)

array([[5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2]])

In [18]:
np.zeros_like(temp)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones_like(temp)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [21]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [22]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [24]:
np.linspace(0, 2, 9) # 函数 linspace , 它接收我们想要的元素数量而不是步长作为参数
# 输出9个数它们之间的距离相同

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
from numpy import pi

# 用于在很多点上求函数值
np.linspace(0, 2*pi, 50)

array([0.        , 0.12822827, 0.25645654, 0.38468481, 0.51291309,
       0.64114136, 0.76936963, 0.8975979 , 1.02582617, 1.15405444,
       1.28228272, 1.41051099, 1.53873926, 1.66696753, 1.7951958 ,
       1.92342407, 2.05165235, 2.17988062, 2.30810889, 2.43633716,
       2.56456543, 2.6927937 , 2.82102197, 2.94925025, 3.07747852,
       3.20570679, 3.33393506, 3.46216333, 3.5903916 , 3.71861988,
       3.84684815, 3.97507642, 4.10330469, 4.23153296, 4.35976123,
       4.48798951, 4.61621778, 4.74444605, 4.87267432, 5.00090259,
       5.12913086, 5.25735913, 5.38558741, 5.51381568, 5.64204395,
       5.77027222, 5.89850049, 6.02672876, 6.15495704, 6.28318531])

In [32]:
a = np.arange(6)                        
print(a)

[0 1 2 3 4 5]


In [33]:
b = np.arange(12).reshape(4, 3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [34]:
c = np.arange(24).reshape(2, 3, 4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [36]:
b**2

array([0, 1, 4, 9])

In [37]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [38]:
# 使用不等号运算符, 会得到一个布尔型数组
a < 35

array([ True,  True, False, False])

In [39]:
a[a < 35]

array([20, 30])

In [41]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x * y

array([ 2.,  8., 18.])

In [42]:
x / y

array([0.5, 0.5, 0.5])

In [44]:
# 与许多矩阵语言不同，乘法运算符 * 的运算在NumPy数组中是元素级别的。矩阵乘积可以使用 dot 函数或方法执行：
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A * B    

array([[2, 0],
       [0, 4]])

In [45]:
A.dot(B)  

array([[5, 4],
       [3, 4]])

In [46]:
# 或者
np.dot(A, B)  

array([[5, 4],
       [3, 4]])

In [47]:
a = np.ones((2, 3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [51]:
b = np.random.random((2, 3)) # [0, 1)中取随机数
b += a
b

array([[3.00616991, 3.10400097, 3.89002911],
       [3.25371207, 3.18019786, 3.96739898]])

In [52]:
a = np.linspace(0, pi, 3)
a.dtype

dtype('float64')

In [53]:
b = np.ones(3, dtype=np.int32)
c = a + b
print(c)
print(c.dtype)

[1.         2.57079633 4.14159265]
float64


In [58]:
a = np.random.random((2,3))
a, a.sum(), a.min(), a.max(), a.argmax() # 返回数组最大值的索引

(array([[0.06523989, 0.20977829, 0.1495119 ],
        [0.93234691, 0.30003305, 0.09771168]]),
 np.float64(1.7546217168356901),
 np.float64(0.06523988541094805),
 np.float64(0.93234691050959),
 np.int64(3))

In [59]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [61]:
b.sum(axis=1)

array([ 6, 22, 38])

In [62]:
b.min(axis=1) 

array([0, 4, 8])

In [63]:
b.cumsum(axis=1)  # 每一行的累积和

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [67]:
c = np.arange(24).reshape(2, 3, 4)
c, c.argmax(axis=0), c.argmax(axis=1), c.argmax(axis=2)

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[2, 2, 2, 2],
        [2, 2, 2, 2]]),
 array([[3, 3, 3],
        [3, 3, 3]]))

In [68]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10])
A * B  # 广播机制

array([[10, 20],
       [30, 40]])

In [69]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(B.shape)
A * B

(2,)


array([[10, 40],
       [30, 80]])

In [72]:
B = np.arange(3)
B, np.exp(B), np.sqrt(B)

(array([0, 1, 2]),
 array([1.        , 2.71828183, 7.3890561 ]),
 array([0.        , 1.        , 1.41421356]))

In [73]:
C = np.array([2., -1., 4.])
np.add(B, C) 

array([2., 0., 6.])

In [74]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [75]:
a[2]

np.int64(8)

In [76]:
a[2:5]

array([ 8, 27, 64])

In [77]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [78]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [80]:
a[[1,3]]

array([ 1, 27])

In [81]:
a = np.arange(10)**3
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [82]:
def f(x, y):
    return 10 * x + y

# https://numpy.org/doc/stable/reference/generated/numpy.fromfunction.html
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [83]:
b[2, 3]

np.int64(23)

In [84]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [85]:
b[:, 1] 

array([ 1, 11, 21, 31, 41])

In [86]:
b[1:3, :] 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [87]:
b[-1] 

array([40, 41, 42, 43])

In [88]:
c = np.array( [[[  0,  1,  2],
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape    

(2, 2, 3)

In [89]:
c[1,...]  # 三个点（ ... ）表示产生完整索引元组所需的冒号。相当于 c[1,:,:] 或 c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [90]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [91]:
c[...,].shape

(2, 2, 3)

In [94]:
list1 = [2, 3, 4, 5]
list2 = list1       # list1和list2共享引用
list2[0] = -1
print(list1, list2)

[-1, 3, 4, 5] [-1, 3, 4, 5]


In [100]:
list1 = [2, 3, 4, 5]
list2 = list1[:]    # 对列表切片返回副本, list2这时是list1的副本
list2[0] = -1
print(list1, list2)

[2, 3, 4, 5] [-1, 3, 4, 5]


In [101]:
a = np.arange(12).reshape(3, 4)
b = a[0,:]          # 对numpy数组切片返回视图
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]


In [102]:
b[0] = 99
print(a)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [104]:
a = np.arange(12).reshape(3, 4)
b = a[0,:].copy() # 返回副本
b[0] = 99
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[99  1  2  3]


In [105]:
b = np.arange(12).reshape(3, 4)
for row in b:
    print(row, end='\n\n')

[0 1 2 3]

[4 5 6 7]

[ 8  9 10 11]



In [106]:
c = np.arange(24).reshape(2, 3, 4)
for row in c:
    print(row, end='\n\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [107]:
for element in b.flat:  # 如果想要对数组中的每个元素执行操作，可以使用 flat 属性，该属性是数组中所有元素的迭代器：
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


In [108]:
# 或者使用 flatten() 方法将数组转换为一维数组，然后进行迭代：
for element in b.flatten():
    print(element)
b.flatten()

0
1
2
3
4
5
6
7
8
9
10
11


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
# numpy.nditer 提供了一种迭代访问多维数组元素的方式：
a = np.arange(10, 16).reshape(2,3)
for x in np.nditer(a):
    print(x)
np.nditer(a)

10
11
12
13
14
15


In [113]:
it = np.nditer(a, flags=['c_index']) # 创建迭代器，flags=['c_index'] 表示使用 C 顺序的索引
while not it.finished:
    print(it.index, it.value) # 打印当前索引和值
    it.iternext() # 移动到下一个元素，直到 it.finished 为 True。

0 10
1 11
2 12
3 13
4 14
5 15


In [114]:
it = np.nditer(a, flags=['multi_index'])   # 'multi_index'：获取多维索引（如 (0, 0)、(0, 1)）。
while not it.finished:
    print(it.multi_index, it.value)
    it.iternext()

(0, 0) 10
(0, 1) 11
(0, 2) 12
(1, 0) 13
(1, 1) 14
(1, 2) 15


In [115]:
arr = np.arange(12).reshape(3,4)
arr, arr.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [116]:
arr.ravel(), arr.reshape(6, 2), arr.T, arr.T.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 (4, 3))

In [117]:
print(arr.shape)
arr.reshape(4, -1)

(3, 4)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### ravel() 与 flatten()：
在 NumPy 中，ravel() 和 flatten() 都是用于将多维数组展平（变成一维数组）的方法，但它们在内存处理和返回结果上有重要区别：

ravel():
* 返回视图（view）（如果可能）, 不复制数据（除非原数组内存不连续，如转置后的数组）。
* 比 flatten() 更快，因为不创建副本。
* 如果原数组是 C 连续（order='C'），则 ravel() 会返回 C 顺序的一维数组；如果是 F 连续（order='F'），则返回 F 顺序的一维数组。

flatten():
* 总是返回副本（copy），不会影响原数组。
* 比 ravel() 慢，因为要分配新内存。
* 默认按 'C'（行优先）顺序展平

两者都支持 order 参数，控制展平的顺序：
* 'C'（默认）：按行展平（C 顺序，行优先）。
* 'F'：按列展平（Fortran 顺序，列优先）。
* 'A'：保持原数组的内存顺序（尽量不转置）。
* 'K'：按元素在内存中的出现顺序展平（尽量保持原顺序）

In [118]:
second = arr.ravel() 
print(second)
third = arr.flatten() 
print(third)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [119]:
second[0] = 88
print(arr)

[[88  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [120]:
third[0] = 99
print(arr)

[[88  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 堆叠数组

In [121]:
a = np.arange(0,6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a, b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [122]:
c = np.vstack((a,b))  # 
print(c.shape)
print(c)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [123]:
d = np.hstack((a,b))  #
print(d.shape)
print(d)

(2, 6)
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [124]:
e = np.dstack((a,b)) # 
print(e.shape)
print(e)

(2, 3, 2)
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


####  随机数函数

In [125]:
np.random.seed(1234)    #设置随机种子为1234

In [126]:
np.random.rand(2, 3)    # numpy.random.rand() 产生一个给定形状的数组，数组中的值服从 [0, 1)之间的均匀分布。

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261]])

In [127]:
np.random.random((2,3)) #同上

array([[0.27646426, 0.80187218, 0.95813935],
       [0.87593263, 0.35781727, 0.50099513]])

In [128]:
np.random.uniform(1, 10, (3, 2)) # numpy.random.uniform(low=0.0, high=1.0, size=None) 返回一个在区间 [low, high) 中均匀分布的数组。

array([[7.15116642, 7.41431824],
       [4.33225679, 6.05076567],
       [5.52774849, 1.12391605]])

In [129]:
np.random.randn(3, 2) # 数组中的值服从标准正态分布。

array([[ 0.40545341,  0.28909194],
       [ 1.32115819, -1.54690555],
       [-0.20264632, -0.65596934]])

In [130]:
np.random.normal(1, 0.2, (3, 2))
# numpy.random.normal(loc=0.0, scale=1.0, size=None) 返回一个由size指定形状的数组，数组中的值服从 均值=loc, 标准差=scale的正态分布。

array([[1.03868428, 1.11068778],
       [1.26363031, 0.90613894],
       [1.13511082, 0.63659455]])

In [131]:
np.random.randint(1, 10, (3, 2))
# numpy.random.randint(low, high=None, size=None, dtype='l') 返回一个在区间 [low, high)中离散均匀抽样的数组，size指定形状，dtype指定数据类型。

array([[2, 8],
       [5, 1],
       [6, 2]], dtype=int32)

In [132]:
np.random.choice(9)
# numpy.random.choice(a,size=None,replace=True,p=None) 若a为数组，则从a中选取元素；若a为单个int类型数，则选取range(a)中的数

5

In [133]:
np.random.choice([0,2,4,6,8,10,12])

np.int64(2)

#### 存取操作
NumPy 提供了存取数组内容的文件操作函数，存取数组数据的文件可以是二进制格式或者文本格式。

tofile():将数组保存到文件
* 默认以二进制格式存储（无分隔符，无元数据）。
* 不保存数组形状或数据类型，仅存储原始数据（需手动记录）。
* 比 np.save() 更底层，但兼容性较差。

fromfile()：从文件加载数组
* 必须明确知道数据的 dtype 和 shape，否则无法正确恢复数组。
* 适用于由 tofile() 生成的文件。

In [156]:
a = np.arange(12).reshape(3, 4)
a.dtype, a.tofile('array.raw')

(dtype('int64'), None)

In [154]:
b = np.fromfile('array.raw', dtype=np.int64)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [155]:
b = np.fromfile('array.raw', dtype=np.int64).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

save()，load()\
它们用来存取 NumPy 专用的二进制格式保存数据（默认文件后缀名.npy），它们会自动处理元素类型和形状等信息。

In [157]:
np.save('arr.npy', a)

In [158]:
c = np.load('arr.npy')
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

savetxt()，loadtxt()\
只能存取一维或二维数组的文本文件, 可以用来读写csv格式文件

In [160]:
# 默认按照'%.18e'格式保存数值，空格分隔
np.savetxt('a1.txt', a)

In [161]:
np.loadtxt('a1.txt')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [162]:
np.savetxt('a2.txt', a, fmt='%d', delimiter=',')  # fmt='%d' 指定数据以整数格式保存
# delimiter=',' 表示用逗号分隔各数值

In [165]:
np.loadtxt('a2.txt', delimiter=',') # delimiter=',' 指定分隔符是逗号（需与保存时一致）

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

#### 其它常用操作

In [166]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr.dtype)
print(arr)

int64
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [167]:
b = arr.astype(np.float64)
print(b.dtype)
print(b)

float64
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [168]:
print(arr.T.shape)
print(arr.T)

(4, 3, 2)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [169]:
arr.transpose(2, 1, 0)   # transpose() 可以完全重新排列数组的所有维度。参数是一个元组，表示新的维度顺序。
# arr.transpose(2, 1, 0) 表示：原来的第 2 维（axis=2）变成新的第 0 维
# 原来的第 1 维（axis=1）保持不变, 原来的第 0 维（axis=0）变成新的第 2 维

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [170]:
arr.swapaxes(0, 1)   # swapaxes() 用于交换两个指定的维度，其他维度保持不变。

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [172]:
a = np.arange(10)
a.clip(1, 8), a  # clip() 不会修改原数组，而是返回一个新数组。
# clip(min, max)：限制数组元素在 [min, max] 范围内
# 所有 <min 的值被替换为 min, 所有 >max 的值被替换为 max

(array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [173]:
a.clip(3, 6, out=a), a

(array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6]), array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6]))